core/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import (
    core_home,
    core_turma_lista,
    core_gerenciar_turma,
    core_lista_dias,
    core_apagar_turma,
    core_aluno_home,
    core_gerenciar_dia,
    core_aluno_lista_turma,
    core_aluno_turma_gerenciar,
    core_aluno_dia_gerenciar,
    core_aluno_dia_arquivado_lista,
    core_aluno_dia_arquivado_gerenciar,
    core_turma_dia_gerenciar,
    core_turma_cadastrar,
    core_turma_dia_rota,
    core_aluno_atualizar,
    core_motorista_atualizar,
    core_aluno_rota,
    core_turma_dia_rota_volta,
    core_apagar_aluno,
    core_rota_todos,
    core_aluno_turma_sair,
)
urlpatterns = [
    # motorista

    path('motorista', core_home, name='core_home'),
    # lista das turmas
    path('motorista/turma', core_turma_lista, name='core_turma_lista'),


    # cadastrar turma
    path('motorista/turma/cadastrar', core_turma_cadastrar,
         name='core_turma_cadastrar'),

    # gerenciar uma turma especifica
    path('motorista/turma/gerenciar/<int:id>', core_gerenciar_turma,
         name='core_gerenciar_turma'),
    # lista dos dias
    path('motorista/turma/dia/lista/<int:id>',
         core_lista_dias, name='core_lista_dias'),
    # remover uma turma
    path('motorista/turma/remover/<int:id>',
         core_apagar_turma, name='core_apagar_turma'),

    # gerenciar um dia especifico
    path('motorista/turma/dia/<int:id>',
         core_gerenciar_dia, name='core_gerenciar_dia'),
    # gerenciar um aluno menor de idade
    path('motorista/turma/dia/<int:idDia>/aluno/<int:idAluno>',
         core_turma_dia_gerenciar, name='core_turma_dia_gerenciar'),

    path('motorista/turma/dia/<int:idDia>/rota',
         core_turma_dia_rota, name='core_turma_dia_rota'),

    path('motorista/turma/dia/voltar/<int:idDia>/rota',
         core_turma_dia_rota_volta, name='core_turma_dia_rota_volta'),

    path('motorista/update/<int:id>', core_motorista_atualizar,
         name='core_motorista_atualizar'),

    path('motorista/turma/<int:idTurma>/aluno/<int:idAluno>/apagar',
         core_apagar_aluno, name='core_apagar_aluno'),

    path('motorista/turma/<int:idTurma>/rota/geral',
         core_rota_todos, name='core_rota_todos'),
    # aluno
    # home do aluno
    path('aluno', core_aluno_home, name='core_aluno_home'),

    # lista de turmas as quais o aluno foi inserido
    path('aluno/turma/lista', core_aluno_lista_turma,
         name='core_aluno_lista_turma'),

    # gerenciamento de uma turma especifica
    path('aluno/turma/gerenciar/<int:idTurma>',
         core_aluno_turma_gerenciar, name='core_aluno_turma_gerenciar'),

    # gerenciamento de um dia especifico
    path('aluno/turma/dia/gerenciar/<int:idDia>',
         core_aluno_dia_gerenciar, name='core_aluno_dia_gerenciar'),
    # lista dos dias arquivados
    path('aluno/turma/diaArquivado/<int:idTurma>', core_aluno_dia_arquivado_lista,
         name='core_aluno_dia_arquivado_lista'),

    path('aluno/turmo/diaArquivado/gerenciar/<int:idDia>',
         core_aluno_dia_arquivado_gerenciar, name='core_aluno_dia_arquivado_gerenciar'),

    path('aluno/update/<int:id>', core_aluno_atualizar,
         name='core_aluno_atualizar'),


    path('aluno/dia/<int:idDia>/rota', core_aluno_rota, name='core_aluno_rota'),

    # aluno sair de turma
    path('aluno/turma/<int:idTurma>', core_aluno_turma_sair,
         name='core_aluno_turma_sair'),
]

tccTeste/urls.py
from django.contrib import admin
from django.urls import path, include

from users.forms import (
    ResetPasswordForm,
    NewPasswordForm,
)

from django.contrib.auth import (
    views,
)

urlpatterns = [
    path('', include('users.urls')),
    path('core/', include('core.urls')),
    path('admin/', admin.site.urls),

    path('password_reset', views.PasswordResetView.as_view(
        template_name="users/pass_recover/reset_password.html", form_class=ResetPasswordForm), name='password_reset'),

    path('password-reset/done/', views.PasswordResetDoneView.as_view(
        template_name="users/pass_recover/reset_password_done.html"), name="password_reset_done"),

    path('password-reset-confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(
        template_name="users/pass_recover/reset_password_confirm.html", form_class=NewPasswordForm), name="password_reset_confirm"),

    path('password-reset-complete/', views.PasswordResetCompleteView.as_view(
        template_name="users/pass_recover/reset_password_complete.html"), name="password_reset_complete"),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from users.views import (
    user_register,
    user_login,
    sair,
)
from django.contrib.auth import (
    views,
)

from users.forms import (
    ResetPasswordForm,
    NewPasswordForm,
)

app_name = "user"
urlpatterns = [
    path('', user_login, name='user_login'),
    path('register', user_register, name='user_register'),
    path('sair', sair, name='sair'),


]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from mapbox_location_field.models import LocationField
import datetime
from django.utils import timezone
# Create your models here.


class custom_user(AbstractUser):
    # 1 -> aluno
    # 2 -> motorista
    permissao = models.IntegerField(default=2)
    telefone = models.CharField(max_length=50,  default='1')
    local = LocationField(default=(1.2, 1.2), null=False, map_attrs={
        "style": "mapbox://styles/mapbox/outdoors-v11",
        "zoom": 13,
        "center": [17.031645, 51.106715],
        "cursor_style": 'pointer',
        "marker_color": "red",
        "rotate": False,
        "geocoder": True,
        "fullscreen_button": True,
        "navigation_buttons": True,
        "track_location_button": True,
        "readonly": True,
        "placeholder": "Pick a location on map below",
    })
    data_nascimento = models.DateField(
        auto_now=False, auto_now_add=False, null=False, blank=False, default=timezone.now)
    email = models.EmailField(unique=True)

users/forms.py
from django.forms import ModelForm
from django import forms
from users.models import custom_user


from django.contrib.auth.forms import (
    PasswordResetForm,
    SetPasswordForm,
)


class DateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'
    #input_formats = ['%y-%m-%dT%H:%M']
    # format = '%y-%m-%dT%H:%M'
    pass


class DateInput(forms.DateInput):
    input_type = 'date'


class UserForm(ModelForm):
    class Meta:
        model = custom_user
        fields = ['username', 'password', 'email',
                  'telefone', 'local', 'data_nascimento']
        widgets = {
            'password': forms.PasswordInput(),
            'data_nascimento': DateInput(format='%Y-%m-%d'),
            # 'username': forms.TextInput(attrs={

            # })
        }

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    permissao = forms.ChoiceField(choices=[(1, 'Aluno'), (2, 'Motorista')])


class UserLoginForm(ModelForm):
    class Meta:
        model = custom_user
        fields = ['username', 'password']
        widgets = {
            'password': forms.PasswordInput(),
            'username': forms.TextInput(attrs={'class': 'username_class'}),
        }


class ResetPasswordForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(ResetPasswordForm, self).__init__(*args, **kwargs)

    email = forms.CharField(widget=forms.TextInput(attrs={
        "class": "input",
        "type": "email",
        "placeholder": "enter email-id"
    }))


class NewPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(NewPasswordForm, self).__init__(*args, **kwargs)

    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': "input",
            "type": "password",
            'autocomplete': 'new-password'
        }))

    new_password2 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': "input",
            "type": "password",
            'autocomplete': 'new-password'
        }))

users/views.py
from django.shortcuts import render, redirect
from users.forms import UserForm, UserLoginForm
from users.models import custom_user
from django.contrib.auth import (
    authenticate,
    login,
    logout,
)

import datetime

# Create your views here.


# sair
def sair(request):
    logout(request)

    return redirect('user:user_login')


# login
def user_login(request):
    form = UserLoginForm()
    if request.method == 'POST':
        u = authenticate(
            username=request.POST['username'], password=request.POST['password'])
        if u is not None:
            login(request, u)
            if u.permissao == 1:
                return redirect('core_aluno_home')
            elif u.permissao == 2:
                return redirect('core_home')
        c = {
            'form': form,
            'sucesso': False
        }
        return render(request, 'users/login.html', c)

    c = {
        'form': form,
    }
    return render(request, 'users/login.html', c)


# registrar
def user_register(request):
    form = UserForm()
    if request.method == 'POST':

        f = UserForm(request.POST)
        #form.permissao = request.POST['permissao']
        valido = False
        if f.is_valid():
            valido = True
            u = f.save(commit=False)
            u.date_joined = datetime.date.today()
            # request.POST['permissao']
            u.permissao = f.cleaned_data['permissao']
            u.save()
        c = {
            'form': form,
        }
        if valido:
            c['sucesso'] = True
        else:
            c['sucesso'] = False
        return render(request, 'users/register.html', c)
        # return redirect('user_login')

    c = {
        'form': form,
    }
    return render(request, 'users/register.html', c)

users/templates/users/login.html
{% extends 'base.html' %}

{% block extra_head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/form.css' %}">
{% endblock extra_head %}

{% block conteudo %}
    {% load bootstrap %}
   
    <div class="row" style="margin-top:100px;">
        <div class="col-sm-12 justify-content-center d-flex">
            <div class="formulario tamanhoP">
                <div class="titulo">
                    <h3>Login</h3>
                </div>
                
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="conteudo">
                        {{form|bootstrap }}
                        <input type="submit" value="Logar" class="btn btn-primary">
                    </div>
                    
                </form>
                <div class="center">
                    <a href={% url 'user:user_register' %}>Registrar</a>
                </div>
                <div class="center">
                    <a href={% url 'password_reset' %}>Esqueci a senha</a>
                </div>
                
            </div>
        </div>

    </div>

    <div class="row">
        <div class="col-sm-12 justify-content-center d-flex">
            <div class="tamanhoP">
                {% if sucesso == False %}
                    <p class="center p-3 mb-2 bg-danger text-white">Login não existe</p>
                {% endif %}
                
            
            </div>
        </div>
    </div>
    
    
    
{% endblock conteudo %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block extra_head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/form.css' %}">
{% endblock extra_head %}

{% block conteudo %}
    
    {% load mapbox_location_field_tags %}
    {% location_field_includes %}
    {% include_jquery %}
    {% load bootstrap %}
    <div class="row">
        <div class="col-sm-12 d-flex">
            <a href={% url 'user:user_login' %} style="">voltar</a>
            
        </div>
    </div>
    <div class="row mt-4 mb-5"><!--form-->
        <div class="col-sm-12 justify-content-center d-flex">
            <div class="formulario tamanhoP">
                <div class="titulo">
                    <h3>Registrar</h3>
                
                </div>
                <form action="" method="post">
                    {% csrf_token %}
                    

                    <div class="conteudo">
                        {{form|bootstrap}}
                        <input type="submit" value="Criar" class="btn btn-success">
                    </div>
                
                </form>
                
            </div>
            
            {{ form.media }}
            
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 justify-content-center d-flex">
            <div class="tamanhoP">
                {% if sucesso == True %}
                    <p class="center p-3 mb-2 bg-success text-white">Usuario cadastrado com sucesso</p>
                {% elif sucesso  == False %}
                    <p class="center p-3 mb-2 bg-danger text-white">Erro ao cadastrar o usuario</p>
                {% endif %}
                
            
            </div>
        </div>
    </div>
   
    
{% endblock conteudo %}