core/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import (
    core_home,
    core_turma_lista,
    core_gerenciar_turma,
    core_lista_dias,
    core_apagar_turma,
    core_aluno_home,
    core_gerenciar_dia,
    core_aluno_lista_turma,
    core_aluno_turma_gerenciar,
    core_aluno_dia_gerenciar,
    core_aluno_dia_arquivado_lista,
    core_aluno_dia_arquivado_gerenciar,
    core_turma_dia_gerenciar,
    core_turma_cadastrar,
    core_turma_dia_rota,
    core_aluno_atualizar,
    core_motorista_atualizar,
    core_aluno_rota,
    core_turma_dia_rota_volta,
    core_apagar_aluno,
    core_rota_todos,
    core_aluno_turma_sair,
)
urlpatterns = [
    # motorista

    path('motorista', core_home, name='core_home'),
    # lista das turmas
    path('motorista/turma', core_turma_lista, name='core_turma_lista'),


    # cadastrar turma
    path('motorista/turma/cadastrar', core_turma_cadastrar,
         name='core_turma_cadastrar'),

    # gerenciar uma turma especifica
    path('motorista/turma/gerenciar/<int:id>', core_gerenciar_turma,
         name='core_gerenciar_turma'),
    # lista dos dias
    path('motorista/turma/dia/lista/<int:id>',
         core_lista_dias, name='core_lista_dias'),
    # remover uma turma
    path('motorista/turma/remover/<int:id>',
         core_apagar_turma, name='core_apagar_turma'),

    # gerenciar um dia especifico
    path('motorista/turma/dia/<int:id>',
         core_gerenciar_dia, name='core_gerenciar_dia'),
    # gerenciar um aluno menor de idade
    path('motorista/turma/dia/<int:idDia>/aluno/<int:idAluno>',
         core_turma_dia_gerenciar, name='core_turma_dia_gerenciar'),

    path('motorista/turma/dia/<int:idDia>/rota',
         core_turma_dia_rota, name='core_turma_dia_rota'),

    path('motorista/turma/dia/voltar/<int:idDia>/rota',
         core_turma_dia_rota_volta, name='core_turma_dia_rota_volta'),

    path('motorista/update/<int:id>', core_motorista_atualizar,
         name='core_motorista_atualizar'),

    path('motorista/turma/<int:idTurma>/aluno/<int:idAluno>/apagar',
         core_apagar_aluno, name='core_apagar_aluno'),

    path('motorista/turma/<int:idTurma>/rota/geral',
         core_rota_todos, name='core_rota_todos'),
    # aluno
    # home do aluno
    path('aluno', core_aluno_home, name='core_aluno_home'),

    # lista de turmas as quais o aluno foi inserido
    path('aluno/turma/lista', core_aluno_lista_turma,
         name='core_aluno_lista_turma'),

    # gerenciamento de uma turma especifica
    path('aluno/turma/gerenciar/<int:idTurma>',
         core_aluno_turma_gerenciar, name='core_aluno_turma_gerenciar'),

    # gerenciamento de um dia especifico
    path('aluno/turma/dia/gerenciar/<int:idDia>',
         core_aluno_dia_gerenciar, name='core_aluno_dia_gerenciar'),
    # lista dos dias arquivados
    path('aluno/turma/diaArquivado/<int:idTurma>', core_aluno_dia_arquivado_lista,
         name='core_aluno_dia_arquivado_lista'),

    path('aluno/turmo/diaArquivado/gerenciar/<int:idDia>',
         core_aluno_dia_arquivado_gerenciar, name='core_aluno_dia_arquivado_gerenciar'),

    path('aluno/update/<int:id>', core_aluno_atualizar,
         name='core_aluno_atualizar'),


    path('aluno/dia/<int:idDia>/rota', core_aluno_rota, name='core_aluno_rota'),

    # aluno sair de turma
    path('aluno/turma/<int:idTurma>', core_aluno_turma_sair,
         name='core_aluno_turma_sair'),
]

tccTeste/urls.py
from django.contrib import admin
from django.urls import path, include

from users.forms import (
    ResetPasswordForm,
    NewPasswordForm,
)

from django.contrib.auth import (
    views,
)

urlpatterns = [
    path('', include('users.urls')),
    path('core/', include('core.urls')),
    path('admin/', admin.site.urls),

    path('password_reset', views.PasswordResetView.as_view(
        template_name="users/pass_recover/reset_password.html", form_class=ResetPasswordForm), name='password_reset'),

    path('password-reset/done/', views.PasswordResetDoneView.as_view(
        template_name="users/pass_recover/reset_password_done.html"), name="password_reset_done"),

    path('password-reset-confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(
        template_name="users/pass_recover/reset_password_confirm.html", form_class=NewPasswordForm), name="password_reset_confirm"),

    path('password-reset-complete/', views.PasswordResetCompleteView.as_view(
        template_name="users/pass_recover/reset_password_complete.html"), name="password_reset_complete"),
]

users/urls.py
from django.contrib import admin
from django.urls import path
from users.views import (
    user_register,
    user_login,
    sair,
)
from django.contrib.auth import (
    views,
)

from users.forms import (
    ResetPasswordForm,
    NewPasswordForm,
)

app_name = "user"
urlpatterns = [
    path('', user_login, name='user_login'),
    path('register', user_register, name='user_register'),
    path('sair', sair, name='sair'),


]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    

    <!--jquery-->

    
   <!-- <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
   -->
  
    <!--<script src=" https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" ></script>-->

    <script src="{% static '/js/jquery-3.5.1.min.js' %}"></script>
    
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    -->
    
    

    <!--bootstrap-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>
   
    <!--mapbox-->
   

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.0.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.0.0/mapbox-gl.css' rel='stylesheet' />


    
   <script
        src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.0/mapbox-gl-directions.js"></script>
    <link rel="stylesheet"
        href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.1.0/mapbox-gl-directions.css"
        type="text/css" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}">


    <script src="https://kit.fontawesome.com/105091f430.js" crossorigin="anonymous"></script>
    {% block extra_head %}{% endblock extra_head %}
    <style>
        .cc{
             min-height:500px;
        }
    </style>
    
    <title>
    {% block titulo %}
        Titulo padrão
    {% endblock titulo %}
    </title>
</head>
<body>
    
    <div class="container-fluid cc">
        {% block conteudo %}
            Conteudo padrão
        {% endblock conteudo %}
    </div>
    
</body>
</html>

templates/delete_confirm.html
{% extends 'base.html' %}


{% block extra_head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'users/css/form.css' %}">
{% endblock extra_head %}

{% block conteudo %}
    <div class="row">
        <div class="col-sm-12 justify-content-center d-flex mt-3">
            
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 justify-content-center d-flex mt-5">
            <div class="formulario tamanhoP">
                <div class="titulo">
                    <h3>{{message}}</h3>
                </div>
                <form action="" method="post">
                    {% csrf_token %}
                    
                    <div class="conteudo">
                        <input type="submit" class="btn btn-danger" value="Confirmar">
                    </div>
                </form>

            </div>
            
        </div>
    </div>

{% endblock conteudo %}

templates/footer.html
<!-- Footer -->
<footer class="page-footer font-small pt-4 ">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">footer</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

templates/menu.html
{% if user.permissao == 1 %}<!--Aluno-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Aluno</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                
                <!--Home-->
                
                <li class="nav-item 
                    {% if ativo == 'home'  %}
                        active
                    
                    {% endif %}">
                
                    <a class="nav-link" href={% url 'core_aluno_home' %}>Home</a>
                </li>
                
                
                <!--Turmas-->
                
                <li class="nav-item 
                
                {% if ativo == 'turma' %}
                    active
                {% endif %}">
            
                    <a class="nav-link" href={% url 'core_aluno_lista_turma' %}>Turma</a>
                </li>

                <!--Update-->
                
                <li class="nav-item {% if ativo == 'update'  %} active {% endif %}">
                
                    <a class="nav-link" href={% url 'core_aluno_atualizar' user.id %}>Atualizar</a>
                </li>


                <!--Sair-->
                <li class="nav-item">
                    <a class="nav-link" href={% url 'user:sair' %}>Sair</a>
                </li>
            </ul>
        </div>
    </nav>
{% elif user.permissao == 2 %}<!--Motorista-->
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Motorista</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                

                <!--Home-->
              
                <li class="nav-item  {% if ativo == 'home'  %} active {% endif %}">
                
                
                    <a class="nav-link" href={% url 'core_home' %}>Home <span class="sr-only">(current)</span></a>
                </li> 

                
                    
                
                   


                <!--Turma-->
                
                <li class="nav-item {% if ativo == 'turma'  %} active {% endif %}">
                
                
                    <a class="nav-link" href={% url 'core_turma_lista' %}>Turma</a>
                </li>


                <!--Update-->
                
                <li class="nav-item {% if ativo == 'update'  %} active {% endif %}">
                
                
                    <a class="nav-link" href={% url 'core_motorista_atualizar' user.id %}>Atualizar</a>
                </li>
                <!--Sair-->
                <li class="nav-item">
                    <a class="nav-link" href={% url 'user:sair' %}>Sair</a>
                </li>
            </ul>
        </div>
    </nav>
{% endif %}



{% comment %}
    
{% endcomment %}
    